# Generated by Django 2.2.12 on 2020-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='client/')),
            ],
        ),
    ]
