# Generated by Django 2.2.12 on 2020-09-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200924_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='link',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
